environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PowerShellEdition: PowerShellCore
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PowerShellEdition: WindowsPowerShell
  snowflake:
    secure: MrRpgZA68/UjPLFWrIzXyQ3T6abvamyK7P9pU0TiS2MowX4I5TMrCnbzbJP6C7HF
  clone_folder: c:\projects\PSDsHook

version: 0.1.0.{build}
skip_commits:
  message: /updated readme.*|update readme.*s/
build: off

#Kick off the CI/CD pipeline
#- ps:   if ($env:PowerShellEdition -eq 'WindowsPowerShell') { . .\build.ps1 -Task Test }
test_script:  
  - pwsh: if ($env:PowerShellEdition -eq 'PowerShellCore')    { . .\build.ps1 -Task Publish }