environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PowerShellEdition: PowerShellCore
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PowerShellEdition: WindowsPowerShell
  snowlake:
    secure: Zt3GFGm4t5NPZtTsYS9KjOszm8tRjZ4dfuygdPdXq5bGKd+36Y3HOQ07uAn1a9ah

version: 0.1.0.{build}
skip_commits:
  message: /updated readme.*|update readme.*s/
build: off

#Kick off the CI/CD pipeline
#- ps:   if ($env:PowerShellEdition -eq 'WindowsPowerShell') { . .\build.ps1 -Task Test }
test_script:  
  - pwsh: if ($env:PowerShellEdition -eq 'PowerShellCore')    { . .\build.ps1 -Task Publish }